### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by kai0416s** [igizuxo/TSC-PCAC#2]
Thank you for your  excellent work.
I have a question for you, in this paper your performance(RD Curve) have five checkpoints , but in your provide link just have R0.
Looking forward to your reply.

**Comment by igizuxo** [comment]
There are five checkpoints in the file. I just checked.

**Comment by igizuxo** [comment]
> Thank you for your excellent work. I have a question for you, in this paper your performance(RD Curve) have five checkpoints , but in your provide link just have R0. Looking forward to your reply.
There are five checkpoints in the file. I just checked.

**Comment by kai0416s** [comment]
Thanks for your reply. I check it have R0,R1,R2,R3,R4.

**Comment by kai0416s** [comment]
Another question i found is NameError: name 'all_result' is not defined in codec.py  what is this?
 all_result=all_result.groupby('sequence').mean().reset_index()
